### ISSUE TITLE
Правки по ДЗ 31

### ISSUE THREAD

**Issue by Dexter19** [brovkoanna/brovkoanna.github.io#4]
setTimeout для очікування введення користувача: Використання setTimeout для очікування введення користувача може бути неефективним, оскільки не гарантує, що користувач заповнить поля форми протягом 10 секунд. Краще використовувати подію, яка відбудеться, коли користувач натисне кнопку або якимось іншим чином підтвердить введення.
Перевірка значень полів форми: Ваша перевірка наявності значень полів форми відбувається одразу після виконання setTimeout, що не гарантує, що користувач встигне їх заповнити. Краще виконувати перевірку в момент події, що відбувається після введення користувача.
Недоліки відправлення запиту: У вас немає перевірки статусу запиту перед обробкою відповіді, а також ви звертаєтесь до response перед тим, як він існує. Також вам слід додати обробку помилок для випадку, якщо запит не вдасться.
Ось код з цими покращеннями:
// Функція, яка викликається при введенні користувачем даних у форму
function handleFormInput() {
  const firstName = document.getElementsByName("firstName")[0].value;
  const lastName = document.getElementsByName("lastName")[0].value;
  let title = document.getElementById("waiting");

  // Перевірка, чи заповнені обидва поля
  if (!firstName && !lastName) {
    title.textContent = "I'm miss You";
  } else {
    title.textContent = `Hello ${firstName} ${lastName}!`;
  }
}

// Додавання події на введення даних у форму
document.addEventListener("input", () => {
  setTimeout(handleFormInput, 10000);
});

// Відправлення запиту до сервера та обробка відповіді
let xhr = new XMLHttpRequest();
xhr.open("GET", "https://jsonplaceholder.typicode.com/posts", true);

xhr.onload = function () {
  if (xhr.status >= 200 && xhr.status < 300) {
    let response = JSON.parse(xhr.responseText);
    let markup = response.map(template).join("");
    document.getElementById("demo").innerHTML = markup;
  } else {
    console.error("Request failed with status:", xhr.status);
  }
};

xhr.onerror = function () {
  console.error("Request failed");
};

xhr.send();

// Функція, яка генерує HTML-код для кожного елемента у відповіді
function template(item) {
  return `
    <h3>${item.title}</h3>
    <div>${item.body}</div>
  `;
}

**Comment by brovkoanna** [comment]
Дякую за пораду. Я все виправила але це завдвння було в 30 лекціїб а не 31
